FROM 3.11-bullseye

WORKDIR /root/src/

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get -y install libpq-dev gcc

# add app
COPY ./ .

# install python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt


ENTRYPOINT [ "python3", "main.py" ]